import "./globals.css";
import { Assistant } from "next/font/google";

export const assistant = Assistant({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${assistant.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
